apply_now:
  fields:
    zone:
      selector:
        select:
          options:
            - living_room
            - kitchen
            - bathroom
            - bathroom_fan
      required: false
apply_zone:
  fields:
    zone:
      selector:
        select:
          options:
            - living_room
            - kitchen
            - bathroom
            - bathroom_fan
      required: true
set_apply_active:
  fields:
    active:
      selector:
        boolean:
      required: true
recalculate:
  fields: {}
dry_run:
  fields:
    zone:
      selector:
        select:
          options:
            - living_room
            - kitchen
            - bathroom
            - bathroom_fan
      required: false
update_options:
  fields:
    options:
      selector:
        object:
      required: false
    reset_keys:
      selector:
        object:
      required: false
reset_options:
  fields:
    keys:
      selector:
        object:
      required: true

